name: TestingGrid
favicon: null
layout_spectrum: 0.021326780784875154
typography_spectrum: 0.7529106070287526
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7324707938823849
  lightness: 0.5913102698978037
  saturation: 0.18615856510587037
  rhythmicContrast: 0.8158734948374331
purpose: []
